default_chain: stride-testnet
chains:
  gaia-testnet:
    key: wallet
    chain-id: GAIA
    rpc-addr: http://127.0.0.1:23657      # use your own GAIA RPC endpoint here
    grpc-addr: http://127.0.0.1:22090     # use your own GAIA GRPC endpoint here
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.4
    gas-prices: 0.01uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 40s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: wallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26657      # use your own Stride GRPC endpoint here
    grpc-addr: http://127.0.0.1:26090     # use your own Stride GRPC endpoint here
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.4
    gas-prices: 0.01ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 40s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
